Repository OCA/brand, pull requests merged in 2020-02, with the labels that each got.

#22 [FIX] Correctly set Brand on Invoices created from Contracts
  contract_brand/models/contract.py
Labels: needs review

#23 [12.0][IMP] - Brand field is only editable in draft state for invoice and sale object
  account_brand/models/account_invoice.py
  sale_brand/models/sale_order.py
Labels: approved, ready to merge

#21 [12.0][IMP] Add Company field to Brand form
  brand/views/res_brand.xml
Labels: approved
