Repository OCA/brand, pull requests merged in 2020-10, with the labels that each got.

#42 [13.0][OPT] product_brand performance optimization
  product_brand/models/product_brand.py
Labels: approved, bot is merging ⏳

#24 [ADD] - define allowed payment mode per brand.
  account_payment_mode_brand/README.rst
  account_payment_mode_brand/__init__.py
  account_payment_mode_brand/__manifest__.py
  account_payment_mode_brand/models/__init__.py
  account_payment_mode_brand/models/res_brand.py
  account_payment_mode_brand/models/res_brand_mixin.py
  account_payment_mode_brand/readme/CONTRIBUTORS.rst
  account_payment_mode_brand/readme/DESCRIPTION.rst
  account_payment_mode_brand/readme/USAGE.rst
  account_payment_mode_brand/static/description/icon.png
  account_payment_mode_brand/static/description/index.html
  account_payment_mode_brand/tests/__init__.py
  account_payment_mode_brand/tests/test_account_payment_mode_brand.py
  account_payment_mode_brand/views/account_invoice.xml
  account_payment_mode_brand/views/res_brand.xml
  contract_payment_mode_brand/README.rst
  contract_payment_mode_brand/__init__.py
  contract_payment_mode_brand/__manifest__.py
  contract_payment_mode_brand/readme/CONTRIBUTORS.rst
  contract_payment_mode_brand/readme/DESCRIPTION.rst
  contract_payment_mode_brand/readme/USAGE.rst
  contract_payment_mode_brand/static/description/icon.png
  contract_payment_mode_brand/static/description/index.html
  contract_payment_mode_brand/views/contract_contract.xml
  oca_dependencies.txt
  sale_payment_mode_brand/README.rst
  sale_payment_mode_brand/__init__.py
  sale_payment_mode_brand/__manifest__.py
  sale_payment_mode_brand/readme/CONTRIBUTORS.rst
  sale_payment_mode_brand/readme/DESCRIPTION.rst
  sale_payment_mode_brand/readme/USAGE.rst
  sale_payment_mode_brand/static/description/icon.png
  sale_payment_mode_brand/static/description/index.html
  sale_payment_mode_brand/views/sale_order.xml
  setup/account_payment_mode_brand/odoo/addons/account_payment_mode_brand
  setup/account_payment_mode_brand/setup.py
  setup/contract_payment_mode_brand/odoo/addons/contract_payment_mode_brand
  setup/contract_payment_mode_brand/setup.py
  setup/sale_payment_mode_brand/odoo/addons/sale_payment_mode_brand
  setup/sale_payment_mode_brand/setup.py
Labels: bot is merging ⏳, needs review

#46 [13.0][MIG] - migration: brand_external_report_layout
  brand_external_report_layout/README.rst
  brand_external_report_layout/__init__.py
  brand_external_report_layout/__manifest__.py
  brand_external_report_layout/i18n/brand_external_report_layout.pot
  brand_external_report_layout/models/__init__.py
  brand_external_report_layout/models/res_brand.py
  brand_external_report_layout/readme/CONTRIBUTORS.rst
  brand_external_report_layout/readme/DESCRIPTION.rst
  brand_external_report_layout/readme/ROADMAP.rst
  brand_external_report_layout/readme/USAGE.rst
  brand_external_report_layout/static/description/icon.png
  brand_external_report_layout/static/description/index.html
  brand_external_report_layout/tests/__init__.py
  brand_external_report_layout/tests/test_brand_external_report_layout.py
  brand_external_report_layout/views/report_template.xml
  brand_external_report_layout/views/res_brand.xml
  setup/brand_external_report_layout/odoo/addons/brand_external_report_layout
  setup/brand_external_report_layout/setup.py
Labels: bot is merging ⏳, migration, needs review

#18 [12.0][ADD] - Add analytic brand module
  account_brand/__manifest__.py
  account_brand/models/account_invoice.py
  account_brand/tests/__init__.py
  account_brand/tests/test_account_analytic_invoice.py
  account_brand/views/account_invoice.xml
  analytic_brand/README.rst
  analytic_brand/__init__.py
  analytic_brand/__manifest__.py
  analytic_brand/models/__init__.py
  analytic_brand/models/res_brand.py
  analytic_brand/readme/CONTRIBUTORS.rst
  analytic_brand/readme/DESCRIPTION.rst
  analytic_brand/static/description/icon.png
  analytic_brand/static/description/index.html
  analytic_brand/views/res_brand.xml
  contract_brand/__manifest__.py
  contract_brand/models/contract.py
  contract_brand/tests/test_contract.py
  sale_brand/__manifest__.py
  sale_brand/models/sale_order.py
  sale_brand/tests/test_sale_order.py
  sale_brand/views/sale_views.xml
  setup/analytic_brand/odoo/addons/analytic_brand
  setup/analytic_brand/setup.py
Labels: bot is merging ⏳, needs review

#15 [12.0][IMP] - Add res partner account brand
  account_brand/__manifest__.py
  account_brand/models/__init__.py
  account_brand/models/account_invoice.py
  account_brand/models/res_partner_account_brand.py
  account_brand/security/res_partner_account_brand.xml
  account_brand/tests/__init__.py
  account_brand/tests/test_account_invoice.py
  account_brand/views/res_partner_account_brand.xml
  contract_brand/models/contract.py
  contract_brand/tests/test_contract.py
  sale_brand/models/sale_order.py
  sale_brand/tests/test_sale_order.py
  sale_brand/wizard/sale_make_invoice_advance.py
Labels: bot is merging ⏳, needs review

#45 [13.0][MIG] - migration account_brand + analytic_brand
  account_brand/README.rst
  account_brand/__init__.py
  account_brand/__manifest__.py
  account_brand/i18n/account_brand.pot
  account_brand/i18n/de.po
  account_brand/i18n/es.po
  account_brand/i18n/hr.po
  account_brand/i18n/zh_CN.po
  account_brand/models/__init__.py
  account_brand/models/account_move.py
  account_brand/models/res_partner_account_brand.py
  account_brand/readme/CONFIGURE.rst
  account_brand/readme/CONTRIBUTORS.rst
  account_brand/readme/CREDITS.rst
  account_brand/readme/DESCRIPTION.rst
  account_brand/readme/USAGE.rst
  account_brand/security/res_partner_account_brand.xml
  account_brand/static/description/icon.png
  account_brand/static/description/index.html
  account_brand/tests/__init__.py
  account_brand/tests/test_account_analytic_move.py
  account_brand/tests/test_account_move.py
  account_brand/tests/test_brand_mixin.py
  account_brand/views/account_move_views.xml
  account_brand/views/res_partner_account_brand.xml
  account_brand/wizards/__init__.py
  account_brand/wizards/account_move_reversal.py
  analytic_brand/README.rst
  analytic_brand/__init__.py
  analytic_brand/__manifest__.py
  analytic_brand/i18n/analytic_brand.pot
  analytic_brand/models/__init__.py
  analytic_brand/models/res_brand.py
  analytic_brand/readme/CONTRIBUTORS.rst
  analytic_brand/readme/DESCRIPTION.rst
  analytic_brand/static/description/icon.png
  analytic_brand/static/description/index.html
  analytic_brand/views/res_brand.xml
  brand/__manifest__.py
  brand/models/res_brand_mixin.py
  brand/views/res_config_settings.xml
  setup/account_brand/odoo/addons/account_brand
  setup/account_brand/setup.py
  setup/analytic_brand/odoo/addons/analytic_brand
  setup/analytic_brand/setup.py
Labels: bot is merging ⏳, migration, needs review

#48 [13.0][MIG] - migration contract_brand
  contract_brand/README.rst
  contract_brand/__init__.py
  contract_brand/__manifest__.py
  contract_brand/i18n/contract_brand.pot
  contract_brand/models/__init__.py
  contract_brand/models/contract.py
  contract_brand/readme/CONTRIBUTORS.rst
  contract_brand/readme/DESCRIPTION.rst
  contract_brand/static/description/icon.png
  contract_brand/static/description/index.html
  contract_brand/tests/__init__.py
  contract_brand/tests/test_contract.py
  contract_brand/views/contract.xml
  oca_dependencies.txt
  setup/contract_brand/odoo/addons/contract_brand
  setup/contract_brand/setup.py
Labels: bot is merging ⏳, migration, needs review
