Repository OCA/brand, pull requests merged in 2020-08, with the labels that each got.

#39 Use more permissive license AGPL3 → LGPL3
  brand/README.rst
  brand/__manifest__.py
  brand/models/res_brand.py
  brand/models/res_brand_mixin.py
  brand/models/res_company.py
  brand/models/res_config_settings.py
  brand/security/res_brand.xml
  brand/static/description/index.html
  brand/views/res_brand.xml
  brand/views/res_config_settings.xml
Labels: approved, bot is merging ⏳, needs review

#37 [12.0][FIX] Brand not required on vendor bill
  account_brand/models/account_invoice.py
Labels: approved, bot is merging ⏳

#38 [12.0][FIX] Create credit note with brand
  account_brand/models/account_invoice.py
  account_brand/tests/test_brand_mixin.py
Labels: approved, bot is merging ⏳, ready to merge

#40 [12.0][FIX] report_template o is undefined
  brand_external_report_layout/views/report_template.xml
Labels: bot is merging ⏳
