Repository OCA/brand, pull requests merged in 2021-06, with the labels that each got.

#65 [FIX] - don't set brand analytic account if it's null
  account_brand/models/account_invoice.py
Labels: bot is merging ⏳, needs review

#53 [13.0][IMP] - sale brand analytic account
  .pre-commit-config.yaml
  account_brand/tests/test_account_analytic_invoice.py
  sale_brand/__manifest__.py
  sale_brand/models/sale_order.py
  sale_brand/tests/test_sale_order.py
  sale_brand/views/sale_views.xml
Labels: bot is merging ⏳, needs review

#57 [12.0][FIX] - fix payment_mode domain
  sale_payment_mode_brand/views/sale_order.xml
Labels: bot is merging ⏳, needs review

#55 [12.0][FIX] - run brand change in finalize invoice
  sale_brand/models/sale_order.py
Labels: bot is merging ⏳, needs review

#49 [13.0][ADD] Product brand purchase report
  product_brand_purchase_report/README.rst
  product_brand_purchase_report/__init__.py
  product_brand_purchase_report/__manifest__.py
  product_brand_purchase_report/readme/CONTRIBUTORS.rst
  product_brand_purchase_report/readme/DESCRIPTION.rst
  product_brand_purchase_report/readme/USAGE.rst
  product_brand_purchase_report/reports/__init__.py
  product_brand_purchase_report/reports/purchase_report.py
  product_brand_purchase_report/reports/purchase_report_view.xml
  product_brand_purchase_report/static/description/icon.png
  product_brand_purchase_report/static/description/index.html
  setup/product_brand_purchase_report/odoo/addons/product_brand_purchase_report
  setup/product_brand_purchase_report/setup.py
Labels: bot is merging ⏳, needs review, new module

#52 [13.0][IMP] sale_brand: assign default brand to Sales Teams
  brand/views/res_config_settings.xml
  product_brand/views/product_brand_view.xml
  sale_brand/__manifest__.py
  sale_brand/models/__init__.py
  sale_brand/models/crm_team.py
  sale_brand/models/sale_order.py
  sale_brand/views/crm_team_views.xml
Labels: bot is merging ⏳, needs review

#77 [14.0][MIG] - brand
  brand/README.rst
  brand/__init__.py
  brand/__manifest__.py
  brand/i18n/brand.pot
  brand/models/__init__.py
  brand/models/res_brand.py
  brand/models/res_brand_mixin.py
  brand/models/res_company.py
  brand/models/res_config_settings.py
  brand/readme/CONTRIBUTORS.rst
  brand/readme/CREDITS.rst
  brand/readme/DESCRIPTION.rst
  brand/readme/USAGE.rst
  brand/security/res_brand.xml
  brand/static/description/icon.png
  brand/static/description/index.html
  brand/views/res_brand.xml
  brand/views/res_config_settings.xml
  setup/brand/odoo/addons/brand
  setup/brand/setup.py
Labels: bot is merging ⏳, migration

#78 [14.0] product_brand: name groups in form view
  product_brand/views/product_brand_view.xml
Labels: bot is merging ⏳, enhancement, needs review

#70 [MIG][14.0] Analytic Brand
  analytic_brand/README.rst
  analytic_brand/__init__.py
  analytic_brand/__manifest__.py
  analytic_brand/i18n/analytic_brand.pot
  analytic_brand/models/__init__.py
  analytic_brand/models/res_brand.py
  analytic_brand/readme/CONTRIBUTORS.rst
  analytic_brand/readme/DESCRIPTION.rst
  analytic_brand/static/description/icon.png
  analytic_brand/static/description/index.html
  analytic_brand/views/res_brand.xml
  setup/analytic_brand/odoo/addons/analytic_brand
  setup/analytic_brand/setup.py
Labels: bot is merging ⏳, migration, needs review

#76 [14.0] Add product_brand_multicompany
  product_brand/tests/common.py
  product_brand/tests/test_product_brand.py
  product_brand_multicompany/README.rst
  product_brand_multicompany/__init__.py
  product_brand_multicompany/__manifest__.py
  product_brand_multicompany/models/__init__.py
  product_brand_multicompany/models/product_brand.py
  product_brand_multicompany/readme/CONTRIBUTORS.rst
  product_brand_multicompany/readme/DESCRIPTION.rst
  product_brand_multicompany/security/ir_rule.xml
  product_brand_multicompany/tests/__init__.py
  product_brand_multicompany/tests/test_product_brand.py
  product_brand_multicompany/views/product_brand_view.xml
  setup/product_brand_multicompany/odoo/addons/product_brand_multicompany
  setup/product_brand_multicompany/setup.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#79 [14.0] Add product_brand_tag
  product_brand_tag/README.rst
  product_brand_tag/__init__.py
  product_brand_tag/__manifest__.py
  product_brand_tag/models/__init__.py
  product_brand_tag/models/product_brand.py
  product_brand_tag/models/product_brand_tag.py
  product_brand_tag/readme/CONTRIBUTORS.rst
  product_brand_tag/readme/DESCRIPTION.rst
  product_brand_tag/security/ir.model.access.csv
  product_brand_tag/security/ir_rule.xml
  product_brand_tag/tests/__init__.py
  product_brand_tag/tests/test_product_brand.py
  product_brand_tag/views/product_brand_tag_view.xml
  product_brand_tag/views/product_brand_view.xml
  setup/product_brand_tag/odoo/addons/product_brand_tag
  setup/product_brand_tag/setup.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#80 [14.0] Add product_brand_tag_secondary
  product_brand_tag/models/product_brand_tag.py
  product_brand_tag_secondary/README.rst
  product_brand_tag_secondary/__init__.py
  product_brand_tag_secondary/__manifest__.py
  product_brand_tag_secondary/models/__init__.py
  product_brand_tag_secondary/models/product_brand.py
  product_brand_tag_secondary/models/product_brand_tag.py
  product_brand_tag_secondary/readme/CONTRIBUTORS.rst
  product_brand_tag_secondary/readme/DESCRIPTION.rst
  product_brand_tag_secondary/tests/__init__.py
  product_brand_tag_secondary/tests/test_product_brand.py
  product_brand_tag_secondary/views/product_brand_tag_view.xml
  product_brand_tag_secondary/views/product_brand_view.xml
  setup/product_brand_tag_secondary/odoo/addons/product_brand_tag_secondary
  setup/product_brand_tag_secondary/setup.py
Labels: approved, bot is merging ⏳, enhancement, needs review
