Repository OCA/brand, pull requests merged in 2022-06, with the labels that each got.

#97 [14.0] Improvements setting brand_id via team_id
  .copier-answers.yml
  sale_brand/models/sale_order.py
  sale_brand/tests/test_sale_order.py
Labels: needs review, needs fixing, bot is merging ⏳

#96 [14.0] Improvements setting Brand use level
  account_brand/tests/test_brand_mixin.py
  brand/models/res_brand_mixin.py
Labels: needs review, approved, bot is merging ⏳

#115 [14.0] [IMP] `product_brand`: better position for group by filter in sale.report
  product_brand/reports/sale_report_view.xml
Labels: approved, ready to merge, bot is merging ⏳
