Repository OCA/brand, pull requests merged in 2022-10, with the labels that each got.

#131 [16.0][MIG] - migration brand, account_brand to 16.0
  account_brand/README.rst
  account_brand/__init__.py
  account_brand/__manifest__.py
  account_brand/i18n/account_brand.pot
  account_brand/i18n/de.po
  account_brand/i18n/es.po
  account_brand/i18n/hr.po
  account_brand/i18n/nl.po
  account_brand/i18n/zh_CN.po
  account_brand/models/__init__.py
  account_brand/models/account_move.py
  account_brand/models/res_partner_account_brand.py
  account_brand/readme/CONFIGURE.rst
  account_brand/readme/CONTRIBUTORS.rst
  account_brand/readme/CREDITS.rst
  account_brand/readme/DESCRIPTION.rst
  account_brand/readme/USAGE.rst
  account_brand/security/res_partner_account_brand.xml
  account_brand/static/description/icon.png
  account_brand/static/description/index.html
  account_brand/tests/__init__.py
  account_brand/tests/test_account_move.py
  account_brand/tests/test_brand_mixin.py
  account_brand/views/account_move_views.xml
  account_brand/views/res_partner_account_brand.xml
  account_brand/wizards/__init__.py
  account_brand/wizards/account_move_reversal.py
  brand/README.rst
  brand/__init__.py
  brand/__manifest__.py
  brand/i18n/brand.pot
  brand/i18n/es_AR.po
  brand/i18n/fr_FR.po
  brand/i18n/it.po
  brand/i18n/pl.po
  brand/models/__init__.py
  brand/models/res_brand.py
  brand/models/res_brand_mixin.py
  brand/models/res_company.py
  brand/models/res_config_settings.py
  brand/readme/CONTRIBUTORS.rst
  brand/readme/CREDITS.rst
  brand/readme/DESCRIPTION.rst
  brand/readme/USAGE.rst
  brand/security/res_brand.xml
  brand/static/description/icon.png
  brand/static/description/index.html
  brand/views/res_brand.xml
  brand/views/res_config_settings.xml
  setup/account_brand/odoo/addons/account_brand
  setup/account_brand/setup.py
  setup/brand/odoo/addons/brand
  setup/brand/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#134 [16.0][MIG] - sale_brand migration to 16.0
  sale_brand/README.rst
  sale_brand/__init__.py
  sale_brand/__manifest__.py
  sale_brand/i18n/es_AR.po
  sale_brand/i18n/fr_FR.po
  sale_brand/i18n/hr.po
  sale_brand/i18n/it.po
  sale_brand/i18n/nl.po
  sale_brand/i18n/sale_brand.pot
  sale_brand/i18n/zh_CN.po
  sale_brand/models/__init__.py
  sale_brand/models/crm_team.py
  sale_brand/models/sale_order.py
  sale_brand/readme/CONTRIBUTORS.rst
  sale_brand/readme/CREDITS.rst
  sale_brand/readme/DESCRIPTION.rst
  sale_brand/readme/USAGE.rst
  sale_brand/static/description/icon.png
  sale_brand/static/description/index.html
  sale_brand/tests/__init__.py
  sale_brand/tests/test_sale_order.py
  sale_brand/views/crm_team_views.xml
  sale_brand/views/sale_views.xml
  sale_brand/wizard/__init__.py
  sale_brand/wizard/sale_make_invoice_advance.py
  setup/sale_brand/odoo/addons/sale_brand
  setup/sale_brand/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#124 sale_brand: issue with create payment on sale with required brand
  sale_brand/tests/test_sale_order.py
  sale_brand/wizard/sale_make_invoice_advance.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#127 [CHG] account_brand: ignore required policy on journal entry.
  account_brand/models/account_move.py
  account_brand/tests/test_brand_mixin.py
  brand/models/res_brand_mixin.py
Labels: approved, ready to merge, bot is merging ⏳

#136 sale_brand: fix issue on invoice creation with required brand
  sale_brand/tests/test_sale_order.py
  sale_brand/wizard/sale_make_invoice_advance.py
Labels: needs review, approved, bot is merging ⏳

#137 sale_brand: fix issue on invoice creation with required brand
  sale_brand/__init__.py
  sale_brand/tests/test_sale_order.py
  sale_brand/wizard/__init__.py
  sale_brand/wizard/sale_make_invoice_advance.py
Labels: needs review, approved, bot is merging ⏳

#132 [16.0] [MIG] product_brand
  product_brand/README.rst
  product_brand/__init__.py
  product_brand/__manifest__.py
  product_brand/i18n/ca.po
  product_brand/i18n/de.po
  product_brand/i18n/es.po
  product_brand/i18n/es_AR.po
  product_brand/i18n/fr.po
  product_brand/i18n/fr_FR.po
  product_brand/i18n/hr.po
  product_brand/i18n/it.po
  product_brand/i18n/nb_NO.po
  product_brand/i18n/nl.po
  product_brand/i18n/nl_NL.po
  product_brand/i18n/pl.po
  product_brand/i18n/product_brand.pot
  product_brand/i18n/pt_BR.po
  product_brand/i18n/sl.po
  product_brand/migrations/16.0.1.0.0/post-migrate.py
  product_brand/models/__init__.py
  product_brand/models/product_brand.py
  product_brand/models/product_template.py
  product_brand/readme/CONTRIBUTORS.rst
  product_brand/readme/DESCRIPTION.rst
  product_brand/readme/ROADMAP.rst
  product_brand/readme/USAGE.rst
  product_brand/reports/__init__.py
  product_brand/reports/account_invoice_report.py
  product_brand/reports/account_invoice_report_view.xml
  product_brand/reports/sale_report.py
  product_brand/reports/sale_report_view.xml
  product_brand/security/ir.model.access.csv
  product_brand/static/description/icon.png
  product_brand/static/description/index.html
  product_brand/tests/__init__.py
  product_brand/tests/common.py
  product_brand/tests/test_product_brand.py
  product_brand/views/product_brand_view.xml
  setup/product_brand/odoo/addons/product_brand
  setup/product_brand/setup.py
Labels: needs review, approved, migration, bot is merging ⏳
