Repository OCA/brand, pull requests merged in 2022-09, with the labels that each got.

#123 Update pre-commit
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  account_brand/__manifest__.py
  contract_brand/__manifest__.py
  sale_brand/__manifest__.py
Labels: bot is merging ⏳

#125 Update pre-commit
  .pre-commit-config.yaml
  account_brand/tests/test_account_move.py
  account_brand/tests/test_brand_mixin.py
  brand/models/res_brand_mixin.py
  contract_brand/tests/test_contract.py
  sale_brand/tests/test_sale_order.py
Labels: bot is merging ⏳

#116 [13.0] Add project_task_brand and sale_timesheet_brand
  project_task_brand/README.rst
  project_task_brand/__init__.py
  project_task_brand/__manifest__.py
  project_task_brand/models/__init__.py
  project_task_brand/models/project_task.py
  project_task_brand/readme/CONTRIBUTORS.rst
  project_task_brand/readme/DESCRIPTION.rst
  project_task_brand/readme/USAGE.rst
  project_task_brand/static/description/icon.png
  project_task_brand/static/description/index.html
  project_task_brand/views/project_task.xml
  sale_timesheet_brand/README.rst
  sale_timesheet_brand/__init__.py
  sale_timesheet_brand/__manifest__.py
  sale_timesheet_brand/models/__init__.py
  sale_timesheet_brand/models/sale_order_line.py
  sale_timesheet_brand/readme/CONTRIBUTORS.rst
  sale_timesheet_brand/readme/DESCRIPTION.rst
  sale_timesheet_brand/readme/USAGE.rst
  sale_timesheet_brand/static/description/icon.png
  sale_timesheet_brand/static/description/index.html
  sale_timesheet_brand/tests/__init__.py
  sale_timesheet_brand/tests/test_sale_timesheet_brand.py
  setup/project_task_brand/odoo/addons/project_task_brand
  setup/project_task_brand/setup.py
  setup/sale_timesheet_brand/odoo/addons/sale_timesheet_brand
  setup/sale_timesheet_brand/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#126 [ADD] brand_stock_account
  brand_stock_account/README.rst
  brand_stock_account/__init__.py
  brand_stock_account/__manifest__.py
  brand_stock_account/models/__init__.py
  brand_stock_account/models/account_move.py
  brand_stock_account/readme/CONFIGURE.rst
  brand_stock_account/readme/CONTRIBUTORS.rst
  brand_stock_account/readme/DESCRIPTION.rst
  brand_stock_account/static/description/index.html
  brand_stock_account/tests/__init__.py
  brand_stock_account/tests/test_account_move.py
  setup/brand_stock_account/odoo/addons/brand_stock_account
  setup/brand_stock_account/setup.py
Labels: approved, bot is merging ⏳
