Repository OCA/brand, pull requests merged in 2022-03, with the labels that each got.

#98 [14.0][FIX] brand_external_report_layout.
  brand_external_report_layout/views/report_template.xml
Labels: bot is merging ⏳

#91 [12.0][FIX] brand_external_report_layout.
  brand_external_report_layout/views/report_template.xml
Labels: needs review, bot is merging ⏳

#92 [13.0][FIX] brand_external_report_layout.
  brand_external_report_layout/views/report_template.xml
Labels: needs review, bot is merging ⏳

#94 [12.0][FIX] - add brand_use_level to fields_view_get fields
  brand/models/res_brand_mixin.py
Labels: needs review, bot is merging ⏳

#44 [13.0][ADD] Pricelist brand
  pricelist_brand/README.rst
  pricelist_brand/__init__.py
  pricelist_brand/__manifest__.py
  pricelist_brand/models/__init__.py
  pricelist_brand/models/product_pricelist.py
  pricelist_brand/readme/CONTRIBUTORS.rst
  pricelist_brand/readme/DESCRIPTION.rst
  pricelist_brand/readme/USAGE.rst
  pricelist_brand/static/description/icon.png
  pricelist_brand/static/description/index.html
  pricelist_brand/tests/__init__.py
  pricelist_brand/tests/test_product_pricelist.py
  pricelist_brand/views/product_pricelist.xml
  setup/pricelist_brand/odoo/addons/pricelist_brand
  setup/pricelist_brand/setup.py
Labels: needs review, bot is merging ⏳, new module

#100 [15.0][MIG] - brand
  brand/README.rst
  brand/__init__.py
  brand/__manifest__.py
  brand/i18n/brand.pot
  brand/i18n/fr_FR.po
  brand/i18n/it.po
  brand/models/__init__.py
  brand/models/res_brand.py
  brand/models/res_brand_mixin.py
  brand/models/res_company.py
  brand/models/res_config_settings.py
  brand/readme/CONTRIBUTORS.rst
  brand/readme/CREDITS.rst
  brand/readme/DESCRIPTION.rst
  brand/readme/USAGE.rst
  brand/security/res_brand.xml
  brand/static/description/icon.png
  brand/static/description/index.html
  brand/views/res_brand.xml
  brand/views/res_config_settings.xml
  setup/brand/odoo/addons/brand
  setup/brand/setup.py
Labels: needs review, bot is merging ⏳

#102 [15.0][MIG] - account_brand
  account_brand/README.rst
  account_brand/__init__.py
  account_brand/__manifest__.py
  account_brand/i18n/account_brand.pot
  account_brand/i18n/de.po
  account_brand/i18n/es.po
  account_brand/i18n/hr.po
  account_brand/i18n/nl.po
  account_brand/i18n/zh_CN.po
  account_brand/models/__init__.py
  account_brand/models/account_move.py
  account_brand/models/res_partner_account_brand.py
  account_brand/readme/CONFIGURE.rst
  account_brand/readme/CONTRIBUTORS.rst
  account_brand/readme/CREDITS.rst
  account_brand/readme/DESCRIPTION.rst
  account_brand/readme/USAGE.rst
  account_brand/security/res_partner_account_brand.xml
  account_brand/static/description/icon.png
  account_brand/static/description/index.html
  account_brand/tests/__init__.py
  account_brand/tests/test_account_analytic_move.py
  account_brand/tests/test_account_move.py
  account_brand/tests/test_brand_mixin.py
  account_brand/views/account_move_views.xml
  account_brand/views/res_partner_account_brand.xml
  account_brand/wizards/__init__.py
  account_brand/wizards/account_move_reversal.py
  brand/models/res_brand_mixin.py
  brand/views/res_brand.xml
  setup/account_brand/odoo/addons/account_brand
  setup/account_brand/setup.py
Labels: needs review, bot is merging ⏳

#99 [FIX] account_brand: Allow to selecting the Analytic Account on Lines
  account_brand/models/account_move.py
Labels: bug, needs review, approved, bot is merging ⏳

#103 [FIX] account_brand: Allow to selecting the Analytic Account on Lines
  account_brand/models/account_move.py
Labels: needs review, bot is merging ⏳

#108 [IMP] - dedicated kanban view for res brand
  brand/views/res_brand.xml
Labels: needs review, bot is merging ⏳

#104 [IMP] - add Brand Document Layout
  brand_external_report_layout/__init__.py
  brand_external_report_layout/__manifest__.py
  brand_external_report_layout/models/res_brand.py
  brand_external_report_layout/tests/test_brand_external_report_layout.py
  brand_external_report_layout/wizards/__init__.py
  brand_external_report_layout/wizards/brand_document_layout.py
  brand_external_report_layout/wizards/brand_document_layout.xml
Labels: needs review, bot is merging ⏳

#112 [MIG] - contract_brand migration 15.0
  contract_brand/README.rst
  contract_brand/__init__.py
  contract_brand/__manifest__.py
  contract_brand/i18n/contract_brand.pot
  contract_brand/models/__init__.py
  contract_brand/models/contract.py
  contract_brand/readme/CONTRIBUTORS.rst
  contract_brand/readme/DESCRIPTION.rst
  contract_brand/static/description/icon.png
  contract_brand/static/description/index.html
  contract_brand/tests/__init__.py
  contract_brand/tests/test_contract.py
  contract_brand/views/contract.xml
  setup/contract_brand/odoo/addons/contract_brand
  setup/contract_brand/setup.py
Labels: needs review, bot is merging ⏳

#111 [MIG] - contract_brand migration 14.0
  contract_brand/README.rst
  contract_brand/__init__.py
  contract_brand/__manifest__.py
  contract_brand/i18n/contract_brand.pot
  contract_brand/models/__init__.py
  contract_brand/models/contract.py
  contract_brand/readme/CONTRIBUTORS.rst
  contract_brand/readme/DESCRIPTION.rst
  contract_brand/static/description/icon.png
  contract_brand/static/description/index.html
  contract_brand/tests/__init__.py
  contract_brand/tests/test_contract.py
  contract_brand/views/contract.xml
  setup/contract_brand/odoo/addons/contract_brand
  setup/contract_brand/setup.py
Labels: needs review, bot is merging ⏳

#109 [MIG] - brand_external_report_layout migration 15.0
  brand_external_report_layout/README.rst
  brand_external_report_layout/__init__.py
  brand_external_report_layout/__manifest__.py
  brand_external_report_layout/i18n/brand_external_report_layout.pot
  brand_external_report_layout/models/__init__.py
  brand_external_report_layout/models/res_brand.py
  brand_external_report_layout/readme/CONTRIBUTORS.rst
  brand_external_report_layout/readme/DESCRIPTION.rst
  brand_external_report_layout/readme/ROADMAP.rst
  brand_external_report_layout/readme/USAGE.rst
  brand_external_report_layout/security/brand_document_layout.xml
  brand_external_report_layout/static/description/icon.png
  brand_external_report_layout/static/description/index.html
  brand_external_report_layout/tests/__init__.py
  brand_external_report_layout/tests/test_brand_external_report_layout.py
  brand_external_report_layout/views/report_template.xml
  brand_external_report_layout/views/res_brand.xml
  brand_external_report_layout/wizards/__init__.py
  brand_external_report_layout/wizards/brand_document_layout.py
  brand_external_report_layout/wizards/brand_document_layout.xml
  setup/brand_external_report_layout/odoo/addons/brand_external_report_layout
  setup/brand_external_report_layout/setup.py
Labels: bot is merging ⏳
