Repository OCA/brand, pull requests merged in 2022-12, with the labels that each got.

#143 [FIX] Updated `transfer_field_to_modifiers` method signature
  brand/models/res_brand_mixin.py
Labels: approved, ready to merge, bot is merging ⏳

#140 [FIX] sale_brand: avoid error on brand without website
  sale_brand/models/res_brand.py
Labels: needs review, approved

#148 [FIX][16.0] brand
  brand/models/res_brand_mixin.py
Labels: needs review, approved, bot is merging ⏳
