Repository OCA/brand, pull requests merged in 2023-01, with the labels that each got.

#152 [FIX] brand view in analytic_brand
  analytic_brand/views/res_brand.xml
Labels: approved, ready to merge

#153 [14.0][FIX] product_brand: Error getting sale data when pos_sale module is …
  product_brand/readme/CONTRIBUTORS.rst
  product_brand/reports/sale_report.py
Labels: needs review, approved, bot is merging ⏳

#156 [16.0][FIX] Update copier template
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#147 [16.0][FIX] product_brand: Error getting sale data when pos_sale module is …
  product_brand/readme/CONTRIBUTORS.rst
  product_brand/reports/sale_report.py
Labels: needs review, bot is merging ⏳
