Repository OCA/brand, pull requests merged in 2023-10, with the labels that each got.

#162 [16.0] [ADD] partner_brand
  partner_brand/README.rst
  partner_brand/__init__.py
  partner_brand/__manifest__.py
  partner_brand/data/res_brand_demo.xml
  partner_brand/data/res_partner_demo.xml
  partner_brand/i18n/fr.po
  partner_brand/models/__init__.py
  partner_brand/models/partner.py
  partner_brand/readme/DESCRIPTION.rst
  partner_brand/static/description/brand.png
  partner_brand/static/description/brand_form.png
  partner_brand/static/description/brand_kanban.png
  partner_brand/static/description/brand_tree.png
  partner_brand/static/description/carrouf.png
  partner_brand/static/description/lyon.jpg
  partner_brand/static/description/walmart.jpg
  partner_brand/static/description/walmart.png
  partner_brand/views/partner.xml
  setup/partner_brand/odoo/addons/partner_brand
  setup/partner_brand/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#169 [16.0] [MIG] product_brand_tag
  product_brand_tag/README.rst
  product_brand_tag/__init__.py
  product_brand_tag/__manifest__.py
  product_brand_tag/i18n/it.po
  product_brand_tag/i18n/product_brand_tag.pot
  product_brand_tag/models/__init__.py
  product_brand_tag/models/product_brand.py
  product_brand_tag/models/product_brand_tag.py
  product_brand_tag/models/product_brand_tag_mixin.py
  product_brand_tag/readme/CONTRIBUTORS.rst
  product_brand_tag/readme/DESCRIPTION.rst
  product_brand_tag/security/ir.model.access.csv
  product_brand_tag/security/ir_rule.xml
  product_brand_tag/static/description/icon.png
  product_brand_tag/static/description/index.html
  product_brand_tag/tests/__init__.py
  product_brand_tag/tests/test_product_brand.py
  product_brand_tag/views/product_brand_tag_view.xml
  product_brand_tag/views/product_brand_view.xml
  setup/product_brand_tag/odoo/addons/product_brand_tag
  setup/product_brand_tag/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#172 [ADD][product_brand_mrp] New module
  product_brand_mrp/README.rst
  product_brand_mrp/__init__.py
  product_brand_mrp/__manifest__.py
  product_brand_mrp/i18n/product_brand_mrp.pot
  product_brand_mrp/models/__init__.py
  product_brand_mrp/models/mrp_production.py
  product_brand_mrp/readme/CONTRIBUTORS.rst
  product_brand_mrp/readme/DESCRIPTION.rst
  product_brand_mrp/readme/USAGE.rst
  product_brand_mrp/static/description/icon.png
  product_brand_mrp/static/description/index.html
  product_brand_mrp/views/mrp_production_views.xml
  setup/product_brand_mrp/odoo/addons/product_brand_mrp
  setup/product_brand_mrp/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#171 [16.0] Migrate product_brand_purchase
  product_brand_purchase/README.rst
  product_brand_purchase/__init__.py
  product_brand_purchase/__manifest__.py
  product_brand_purchase/i18n/it.po
  product_brand_purchase/i18n/product_brand_purchase.pot
  product_brand_purchase/readme/CONTRIBUTORS.rst
  product_brand_purchase/readme/DESCRIPTION.rst
  product_brand_purchase/readme/USAGE.rst
  product_brand_purchase/reports/__init__.py
  product_brand_purchase/reports/purchase_report.py
  product_brand_purchase/reports/purchase_report_view.xml
  product_brand_purchase/static/description/icon.png
  product_brand_purchase/static/description/index.html
  product_brand_purchase/views/product_brand_view.xml
  setup/product_brand_purchase/odoo/addons/product_brand_purchase
  setup/product_brand_purchase/setup.py
Labels: approved, bot is merging ⏳

#175 [15.0][IMP] brand: test performance improvement
  product_brand/tests/common.py
Labels: bot is merging ⏳

#176 [16.0][IMP] brand: test performance improvement
  product_brand/tests/common.py
Labels: needs review, approved, bot is merging ⏳

#177 [16.0][brand_external_report_layout][FIX] Add missing sudo() in template
  brand_external_report_layout/views/report_template.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#178 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  brand/i18n/brand.pot
  product_brand/i18n/product_brand.pot
  product_brand/views/product_brand_view.xml
  product_brand_social_responsibility/i18n/product_brand_social_responsibility.pot
  product_brand_social_responsibility/views/product_brand_tag_csr_view.xml
Labels: help wanted, needs review, bot is merging ⏳
