Repository OCA/brand, pull requests merged in 2025-05, with the labels that each got.

#254 [18.0][REF] brand: license to LGPL-3
  brand/README.rst
  brand/__manifest__.py
  brand/models/res_brand.py
  brand/models/res_brand_mixin.py
  brand/models/res_company.py
  brand/models/res_config_settings.py
  brand/security/res_brand.xml
  brand/static/description/index.html
  brand/views/res_brand.xml
  brand/views/res_config_settings.xml
Labels: approved, bot is merging ⏳

#242 [18.0][MIG] stock_brand
  stock_brand/README.rst
  stock_brand/__init__.py
  stock_brand/__manifest__.py
  stock_brand/i18n/nl.po
  stock_brand/i18n/stock_brand.pot
  stock_brand/models/__init__.py
  stock_brand/models/sale_order.py
  stock_brand/models/stock_picking.py
  stock_brand/pyproject.toml
  stock_brand/readme/CONTRIBUTORS.md
  stock_brand/readme/CREDITS.md
  stock_brand/readme/DESCRIPTION.md
  stock_brand/readme/USAGE.md
  stock_brand/static/description/icon.png
  stock_brand/static/description/index.html
  stock_brand/tests/__init__.py
  stock_brand/tests/test_sale_order.py
  stock_brand/views/stock_picking_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#256 [16.0][MIG] stock_brand
  setup/stock_brand/odoo/addons/stock_brand
  setup/stock_brand/setup.py
  stock_brand/README.rst
  stock_brand/__init__.py
  stock_brand/__manifest__.py
  stock_brand/i18n/nl.po
  stock_brand/i18n/stock_brand.pot
  stock_brand/models/__init__.py
  stock_brand/models/sale_order.py
  stock_brand/models/stock_picking.py
  stock_brand/pyproject.toml
  stock_brand/readme/CONTRIBUTORS.md
  stock_brand/readme/CREDITS.md
  stock_brand/readme/DESCRIPTION.md
  stock_brand/readme/USAGE.md
  stock_brand/static/description/icon.png
  stock_brand/static/description/index.html
  stock_brand/tests/__init__.py
  stock_brand/tests/test_sale_order.py
  stock_brand/views/stock_picking_views.xml
Labels: needs review, approved, migration, bot is merging ⏳
