Repository OCA/brand, pull requests merged in 2025-07, with the labels that each got.

#251 [18.0] [MIG] account_payment_mode_brand
  account_payment_mode_brand/18.0.1.0.0/pre-migrate.py
  account_payment_mode_brand/README.rst
  account_payment_mode_brand/__init__.py
  account_payment_mode_brand/__manifest__.py
  account_payment_mode_brand/i18n/account_payment_mode_brand.pot
  account_payment_mode_brand/models/__init__.py
  account_payment_mode_brand/models/res_brand.py
  account_payment_mode_brand/models/res_brand_mixin.py
  account_payment_mode_brand/pyproject.toml
  account_payment_mode_brand/readme/CONTRIBUTORS.md
  account_payment_mode_brand/readme/DESCRIPTION.md
  account_payment_mode_brand/readme/USAGE.md
  account_payment_mode_brand/static/description/icon.png
  account_payment_mode_brand/static/description/index.html
  account_payment_mode_brand/tests/__init__.py
  account_payment_mode_brand/tests/test_account_payment_mode_brand.py
  account_payment_mode_brand/views/account_move.xml
  account_payment_mode_brand/views/res_brand.xml
Labels: approved, ready to merge, bot is merging ⏳

#237 [18.0][MIG] product_brand_tag: Migration to 18.0
  product_brand_tag/README.rst
  product_brand_tag/__init__.py
  product_brand_tag/__manifest__.py
  product_brand_tag/i18n/es.po
  product_brand_tag/i18n/it.po
  product_brand_tag/i18n/product_brand_tag.pot
  product_brand_tag/models/__init__.py
  product_brand_tag/models/product_brand.py
  product_brand_tag/models/product_brand_tag.py
  product_brand_tag/models/product_brand_tag_mixin.py
  product_brand_tag/pyproject.toml
  product_brand_tag/readme/CONTRIBUTORS.md
  product_brand_tag/readme/DESCRIPTION.md
  product_brand_tag/security/ir.model.access.csv
  product_brand_tag/security/ir_rule.xml
  product_brand_tag/static/description/icon.png
  product_brand_tag/static/description/index.html
  product_brand_tag/tests/__init__.py
  product_brand_tag/tests/test_product_brand.py
  product_brand_tag/views/product_brand_tag_view.xml
  product_brand_tag/views/product_brand_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#241 [18.0][MIG] account_invoice_bank_brand
  account_invoice_bank_brand/README.rst
  account_invoice_bank_brand/__init__.py
  account_invoice_bank_brand/__manifest__.py
  account_invoice_bank_brand/models/__init__.py
  account_invoice_bank_brand/models/account_move.py
  account_invoice_bank_brand/models/res_brand.py
  account_invoice_bank_brand/pyproject.toml
  account_invoice_bank_brand/readme/CONTRIBUTORS.md
  account_invoice_bank_brand/readme/DESCRIPTION.md
  account_invoice_bank_brand/readme/USAGE.md
  account_invoice_bank_brand/static/description/icon.png
  account_invoice_bank_brand/static/description/index.html
  account_invoice_bank_brand/tests/__init__.py
  account_invoice_bank_brand/tests/test_account_move.py
  account_invoice_bank_brand/views/res_brand.xml
Labels: needs review, approved, migration, bot is merging ⏳

#234 [18.0][MIG] product_brand_purchase: Migration to 18.0
  product_brand_purchase/README.rst
  product_brand_purchase/__init__.py
  product_brand_purchase/__manifest__.py
  product_brand_purchase/i18n/es.po
  product_brand_purchase/i18n/it.po
  product_brand_purchase/i18n/product_brand_purchase.pot
  product_brand_purchase/pyproject.toml
  product_brand_purchase/readme/CONTRIBUTORS.md
  product_brand_purchase/readme/DESCRIPTION.md
  product_brand_purchase/readme/USAGE.md
  product_brand_purchase/reports/__init__.py
  product_brand_purchase/reports/purchase_report.py
  product_brand_purchase/reports/purchase_report_view.xml
  product_brand_purchase/static/description/icon.png
  product_brand_purchase/static/description/index.html
  product_brand_purchase/tests/__init__.py
  product_brand_purchase/tests/test_product_brand_purchase.py
  product_brand_purchase/views/product_brand_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#232 [18.0][MIG] partner_brand: Migration to 18.0
  partner_brand/README.rst
  partner_brand/__init__.py
  partner_brand/__manifest__.py
  partner_brand/data/res_brand_demo.xml
  partner_brand/data/res_partner_demo.xml
  partner_brand/i18n/es.po
  partner_brand/i18n/fr.po
  partner_brand/i18n/it.po
  partner_brand/i18n/partner_brand.pot
  partner_brand/models/__init__.py
  partner_brand/models/partner.py
  partner_brand/pyproject.toml
  partner_brand/readme/CONTRIBUTORS.md
  partner_brand/readme/DESCRIPTION.md
  partner_brand/static/description/brand.png
  partner_brand/static/description/brand_form.png
  partner_brand/static/description/brand_kanban.png
  partner_brand/static/description/brand_tree.png
  partner_brand/static/description/carrouf.png
  partner_brand/static/description/icon.png
  partner_brand/static/description/index.html
  partner_brand/static/description/lyon.jpg
  partner_brand/static/description/walmart.jpg
  partner_brand/static/description/walmart.png
  partner_brand/tests/__init__.py
  partner_brand/tests/test_partner_brand.py
  partner_brand/views/partner.xml
Labels: approved, migration, ready to merge, bot is merging ⏳

#243 [18.0] [MIG] contract_brand
  contract_brand/README.rst
  contract_brand/__init__.py
  contract_brand/__manifest__.py
  contract_brand/i18n/contract_brand.pot
  contract_brand/i18n/es.po
  contract_brand/models/__init__.py
  contract_brand/models/contract.py
  contract_brand/models/contract_line.py
  contract_brand/pyproject.toml
  contract_brand/readme/CONTRIBUTORS.md
  contract_brand/readme/DESCRIPTION.md
  contract_brand/static/description/icon.png
  contract_brand/static/description/index.html
  contract_brand/tests/__init__.py
  contract_brand/tests/test_contract.py
  contract_brand/views/contract.xml
Labels: approved, ready to merge, bot is merging ⏳
