Repository OCA/brand, pull requests merged in 2025-04, with the labels that each got.

#219 [18.0][MIG] account_brand
  account_brand/README.rst
  account_brand/__init__.py
  account_brand/__manifest__.py
  account_brand/i18n/account_brand.pot
  account_brand/i18n/de.po
  account_brand/i18n/es.po
  account_brand/i18n/es_AR.po
  account_brand/i18n/hr.po
  account_brand/i18n/it.po
  account_brand/i18n/nl.po
  account_brand/i18n/zh_CN.po
  account_brand/models/__init__.py
  account_brand/models/account_move.py
  account_brand/models/res_partner_account_brand.py
  account_brand/pyproject.toml
  account_brand/readme/CONFIGURE.md
  account_brand/readme/CONTRIBUTORS.md
  account_brand/readme/CREDITS.md
  account_brand/readme/DESCRIPTION.md
  account_brand/readme/USAGE.md
  account_brand/security/res_partner_account_brand.xml
  account_brand/static/description/icon.png
  account_brand/static/description/index.html
  account_brand/tests/__init__.py
  account_brand/tests/test_account_move.py
  account_brand/tests/test_brand_mixin.py
  account_brand/views/account_move_views.xml
  account_brand/views/res_partner_account_brand.xml
  account_brand/wizards/__init__.py
  account_brand/wizards/account_move_reversal.py
Labels: approved, ready to merge, bot is merging ⏳

#221 [18.0][MIG] sale_brand
  sale_brand/README.rst
  sale_brand/__init__.py
  sale_brand/__manifest__.py
  sale_brand/i18n/es.po
  sale_brand/i18n/es_AR.po
  sale_brand/i18n/fr_FR.po
  sale_brand/i18n/hr.po
  sale_brand/i18n/it.po
  sale_brand/i18n/nl.po
  sale_brand/i18n/sale_brand.pot
  sale_brand/i18n/zh_CN.po
  sale_brand/models/__init__.py
  sale_brand/models/crm_team.py
  sale_brand/models/sale_order.py
  sale_brand/pyproject.toml
  sale_brand/readme/CONTRIBUTORS.md
  sale_brand/readme/CREDITS.md
  sale_brand/readme/DESCRIPTION.md
  sale_brand/readme/USAGE.md
  sale_brand/static/description/icon.png
  sale_brand/static/description/index.html
  sale_brand/tests/__init__.py
  sale_brand/tests/test_sale_order.py
  sale_brand/views/crm_team_views.xml
  sale_brand/views/sale_views.xml
Labels: approved, migration, bot is merging ⏳

#238 [16.0][REF]brand_external_report_layout: header and footer as Html field.
  brand_external_report_layout/models/res_brand.py
  brand_external_report_layout/wizards/brand_document_layout.py
Labels: approved, ready to merge, bot is merging ⏳

#231 [18.0][MIG] analytic_brand: Migration to 18.0
  analytic_brand/README.rst
  analytic_brand/__init__.py
  analytic_brand/__manifest__.py
  analytic_brand/i18n/analytic_brand.pot
  analytic_brand/i18n/es.po
  analytic_brand/i18n/it.po
  analytic_brand/models/__init__.py
  analytic_brand/models/res_brand.py
  analytic_brand/pyproject.toml
  analytic_brand/readme/CONTRIBUTORS.md
  analytic_brand/readme/DESCRIPTION.md
  analytic_brand/static/description/icon.png
  analytic_brand/static/description/index.html
  analytic_brand/tests/__init__.py
  analytic_brand/tests/test_analytic_brand.py
  analytic_brand/views/res_brand.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
