Repository OCA/brand, pull requests merged in 2025-01, with the labels that each got.

#195 [16.0][FIX] add is_company_detail_empty boolean computed field on res.brand
  brand_external_report_layout/models/res_brand.py
Labels: approved, bot is merging ⏳

#193 [17.0][MIG] account_brand
  account_brand/README.rst
  account_brand/__init__.py
  account_brand/__manifest__.py
  account_brand/i18n/account_brand.pot
  account_brand/i18n/de.po
  account_brand/i18n/es.po
  account_brand/i18n/es_AR.po
  account_brand/i18n/hr.po
  account_brand/i18n/nl.po
  account_brand/i18n/zh_CN.po
  account_brand/models/__init__.py
  account_brand/models/account_move.py
  account_brand/models/res_partner_account_brand.py
  account_brand/pyproject.toml
  account_brand/readme/CONFIGURE.md
  account_brand/readme/CONTRIBUTORS.md
  account_brand/readme/CREDITS.md
  account_brand/readme/DESCRIPTION.md
  account_brand/readme/USAGE.md
  account_brand/security/res_partner_account_brand.xml
  account_brand/static/description/icon.png
  account_brand/static/description/index.html
  account_brand/tests/__init__.py
  account_brand/tests/test_account_move.py
  account_brand/tests/test_brand_mixin.py
  account_brand/views/account_move_views.xml
  account_brand/views/res_partner_account_brand.xml
  account_brand/wizards/__init__.py
  account_brand/wizards/account_move_reversal.py
Labels: bot is merging ⏳

#151 [12.0][ADD] account_invoice_bank_brand
  account_invoice_bank_brand/README.rst
  account_invoice_bank_brand/__init__.py
  account_invoice_bank_brand/__manifest__.py
  account_invoice_bank_brand/models/__init__.py
  account_invoice_bank_brand/models/account_invoice.py
  account_invoice_bank_brand/models/res_brand.py
  account_invoice_bank_brand/readme/CONTRIBUTORS.rst
  account_invoice_bank_brand/readme/DESCRIPTION.rst
  account_invoice_bank_brand/readme/USAGE.rst
  account_invoice_bank_brand/static/description/icon.png
  account_invoice_bank_brand/static/description/index.html
  account_invoice_bank_brand/tests/__init__.py
  account_invoice_bank_brand/tests/test_account_invoice.py
  account_invoice_bank_brand/views/res_brand.xml
  setup/account_invoice_bank_brand/odoo/addons/account_invoice_bank_brand
  setup/account_invoice_bank_brand/setup.py
Labels: help wanted, approved, ready to merge, needs fixing, bot is merging ⏳, no stale

#200 [17.0][MIG] sale_brand
  sale_brand/README.rst
  sale_brand/__init__.py
  sale_brand/__manifest__.py
  sale_brand/i18n/es.po
  sale_brand/i18n/es_AR.po
  sale_brand/i18n/fr_FR.po
  sale_brand/i18n/hr.po
  sale_brand/i18n/it.po
  sale_brand/i18n/nl.po
  sale_brand/i18n/sale_brand.pot
  sale_brand/i18n/zh_CN.po
  sale_brand/models/__init__.py
  sale_brand/models/crm_team.py
  sale_brand/models/sale_order.py
  sale_brand/pyproject.toml
  sale_brand/readme/CONTRIBUTORS.md
  sale_brand/readme/CREDITS.md
  sale_brand/readme/DESCRIPTION.md
  sale_brand/readme/USAGE.md
  sale_brand/static/description/icon.png
  sale_brand/static/description/index.html
  sale_brand/tests/__init__.py
  sale_brand/tests/test_sale_order.py
  sale_brand/views/crm_team_views.xml
  sale_brand/views/sale_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳, no stale

#215 [18.0][MIG] product_brand: Migration to 18.0
  product_brand/README.rst
  product_brand/__init__.py
  product_brand/__manifest__.py
  product_brand/i18n/ca.po
  product_brand/i18n/de.po
  product_brand/i18n/es.po
  product_brand/i18n/es_AR.po
  product_brand/i18n/fr.po
  product_brand/i18n/fr_FR.po
  product_brand/i18n/hr.po
  product_brand/i18n/it.po
  product_brand/i18n/nb_NO.po
  product_brand/i18n/nl.po
  product_brand/i18n/nl_NL.po
  product_brand/i18n/pl.po
  product_brand/i18n/product_brand.pot
  product_brand/i18n/pt.po
  product_brand/i18n/pt_BR.po
  product_brand/i18n/sl.po
  product_brand/models/__init__.py
  product_brand/models/product_brand.py
  product_brand/models/product_template.py
  product_brand/pyproject.toml
  product_brand/readme/CONTRIBUTORS.md
  product_brand/readme/CREDITS.md
  product_brand/readme/DESCRIPTION.md
  product_brand/readme/ROADMAP.md
  product_brand/readme/USAGE.md
  product_brand/reports/__init__.py
  product_brand/reports/account_invoice_report.py
  product_brand/reports/account_invoice_report_view.xml
  product_brand/reports/sale_report.py
  product_brand/reports/sale_report_view.xml
  product_brand/security/ir.model.access.csv
  product_brand/static/description/icon.png
  product_brand/static/description/index.html
  product_brand/tests/__init__.py
  product_brand/tests/common.py
  product_brand/tests/test_product_brand.py
  product_brand/views/product_brand_view.xml
Labels: approved, ready to merge, bot is merging ⏳
